# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/newnbdev',
                'doc_host': 'https://akrishnamo.github.io',
                'git_url': 'https://github.com/akrishnamo/newnbdev',
                'lib_path': 'newnbdev'},
  'syms': {'newnbdev.core': {'newnbdev.core.foo': ('core.html#foo', 'newnbdev/core.py')}}}